"""
MATH 170 - Lab 6: a table for any formula, from the command line.

    python tabulate.py "20*x - 4.9*x**2" 0 4 8

prints the formula at 8 + 1 equally spaced points from 0 to 4.

You do not edit this file. It uses parse_args, make_function and table from
lab06_table.py, which the build cell in lab06.ipynb writes from your work.
"""

import sys
from lab06_table import parse_args, make_function, table

if len(sys.argv) != 5:
    print("tabulate.py needs 4 words after its name: formula a b n")
    print("It got", len(sys.argv) - 1, "of them:", sys.argv[1:])
    print('A formula with spaces must be in quotes: "20*x - 4.9*x**2"')
else:
    formula, a, b, n = parse_args(sys.argv)
    f = make_function(formula)
    xs, ys = table(f, a, b, n)
    print("         x    ", formula)
    for k in range(len(xs)):
        print(f"{xs[k]:10.4f}   {ys[k]:14.6f}")
